# Generated by Django 5.0.3 on 2024-03-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarea_testado_solicitud_testado_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('id_tipo_solicitud', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('id_tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ttipe_document')),
            ],
        ),
    ]
