# Generated by Django 5.0.3 on 2024-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tsolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsolicitud',
            name='archivo_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='nombre_archivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tsolicitud',
            name='archivo',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
