# Generated by Django 5.0.3 on 2024-03-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_testado_usuario_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tEstado_usuario_form',
            new_name='tEstado_Activo',
        ),
        migrations.RenameField(
            model_name='testado_activo',
            old_name='estado',
            new_name='esta_activo',
        ),
    ]
