# Generated by Django 5.0.3 on 2024-03-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_testado_usuario_form_testado_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsolicitud',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='tsolicitud',
            name='nombre_archivo',
        ),
    ]
