# Generated by Django 5.0.3 on 2024-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_tsolicitud_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextendido',
            name='id_estadoU',
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='correo',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='nombre_completo',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='numero_identificacion',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
