# Generated by Django 5.0.3 on 2024-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_usuarioextendido_id_estadou_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextendido',
            name='correo',
        ),
    ]
