# Generated by Django 5.0.3 on 2024-03-21 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_usuarioextendido_es_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsolicitud',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea'),
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='id_esta_activo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.testado_activo'),
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='id_estado_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.testado_solicitud'),
        ),
        migrations.AlterField(
            model_name='tsolicitud',
            name='id_tipo_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ttipo_solicitud'),
        ),
    ]
