# Generated by Django 5.0.3 on 2024-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_tsolicitud_id_area_tsolicitud_id_esta_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsolicitud',
            name='fecha_de_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='fecha_de_registro',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='fecha_de_respuesta_oportuna',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
