# Generated by Django 5.0.3 on 2024-03-22 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_tsolicitud_fecha_de_cierre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tsolicitud',
            name='archivo_respuesta',
            field=models.FileField(null=True, upload_to='respuestas/'),
        ),
        migrations.AddField(
            model_name='tsolicitud',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tsolicitud',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tsolicitud',
            name='id_estado_solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.testado_solicitud'),
        ),
    ]
