# Generated by Django 5.0.3 on 2024-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_usuarioextendido_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttipe_document',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
