# Generated by Django 5.0.3 on 2024-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_tsolicitud_id_nombre_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsolicitud',
            name='politica_privacidad',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
