# Generated by Django 5.0.3 on 2024-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_tsolicitud_politica_privacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsolicitud',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tsolicitud',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
