# Generated by Django 5.0.3 on 2024-05-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_configuracion_correo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tEstado_usuario',
        ),
    ]
