# Generated by Django 5.0.3 on 2024-05-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_delete_testado_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
